--- 
title: "United States Water Levels"
author: "Kylie Brothers, Spencer Davis, and Sheris Johnet"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

  Water is arguably the most important resource on this earth; every living being is dependent on this natural resource for survival. It is a very fragile, essential ecosystem that provides a lot of biodiversity. To create a sustainable future, water levels need to be tracked and recorded to ensure that the bodies of water at the optimal height for sailors and aquatic animals.
	Every time a fisherman or sailor comes into a port, it is important for them to know the depth of the water and if their boat can fit in the shallowest parts of a canal. Sailing ships today are “much larger than the old sailing ships” (US Department of Commerce & National Oceanic and Atmospheric Administration, 2013). This knowledge is also critical because the increased marine traffic leaves no room for error and each vessel must maneuver correctly.
  The Earth is almost two-thirds water. Of that water, lakes contain “77% of the liquid surface fresh water” (Molinos, Viana, Brennan, Donohue, 2015). As water levels change in the lakes, it affects the entire ecosystem around it. Extremely high or extremely low water levels are particularly bad by “altering patterns of sediment deposition and inducing shifts in their trophic state” (Molinos et al., 2015).  In addition, the extremely high water levels cause “shoreline damage” and extremely low water levels “generate water quality issues” (Molinos et al., 2015). Although these extreme shifts in the water levels are detrimental on the ecosystem, the slight fluctuations in water levels are healthy since they balance the water nutrients and regulate the lakes.
  For our project, we will be specifically looking at the recorded water levels for 6 different stations in different regions and states throughout the United States; the stations we will be analyzing are The Battery, NY; Virginia Key, Biscayne Bay, FL; Galveston Pier 21, TX; Monterey, CA; Prudhoe Bay, AK; and Honolulu, HI. We want to compare the water level changes in different parts of the United States to see if any specific area is getting impacted more than other regions. Additionally, we want to look at each station individually to see the potential trends and seasonality in water level readings over the course of 20+ years.




References:
García Molinos J, Viana M, Brennan M, Donohue I (2015). Importance of Long-Term Cycles for Predicting Water Level Dynamics in Natural Lakes. PLoS ONE 10(3): e0119253. doi:10.1371/journal. pone.0119253
US Department of Commerce, & National Oceanic and Atmospheric Administration. (2013, June 01). The Importance of Monitoring the Tides and Their Currents - Tides and Water Levels: NOAA's National Ocean Service Education. Retrieved May 2, 2019, from https://oceanservice.noaa.gov/education/tutorial_tides/tides09_monitor.html
